# Generated by Django 5.0.2 on 2024-02-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_menu_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='Inventory',
            field=models.SmallIntegerField(),
        ),
    ]
